# Copyright (c) 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0 or MIT

import argparse
import hashlib
import json
from pathlib import Path


RUST_HEADER = """// Copyright (c) 2026 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0 or MIT

//
// This is autogenerated file - do not modify it
//

"""


def read_records(filename):
    records = []
    record = {}

    with open(filename, encoding="ascii") as source:
        for line_number, line in enumerate(source, start=1):
            line = line.strip()
            if not line:
                if record:
                    records.append(record)
                    record = {}
                continue
            if line.startswith("#"):
                continue
            if "=" not in line:
                raise ValueError(f"{filename}:{line_number}: expected name = value")

            name, value = (part.strip() for part in line.split("=", 1))
            record[name.lower()] = value

    if record:
        records.append(record)
    return records


def decode_hex(record, name, size):
    try:
        value = bytes.fromhex(record[name])
    except KeyError as error:
        raise ValueError(f"missing {name} field") from error
    except ValueError as error:
        raise ValueError(f"invalid hexadecimal {name} field") from error

    if len(value) != size:
        raise ValueError(f"{name} is {len(value)} bytes; expected {size}")
    return value


def format_bytes(value, indent=8):
    if len(value) == 1:
        return f"&[0x{value[0]:02x}]"
    item_indent = " " * (indent + 4)
    lines = []
    for offset in range(0, len(value), 14):
        chunk = value[offset : offset + 14]
        lines.append(item_indent + "".join(f"0x{byte:02x}, " for byte in chunk).rstrip())
    return "&[\n" + "\n".join(lines) + "\n" + " " * indent + "]"


def render_vector(fields, source=None):
    struct_fields = "\n".join(
        f"    pub {name}: &'a [u8; {len(value)}]," for name, value in fields
    )
    values = "\n".join(
        f"        {name}: {format_bytes(value)}," for name, value in fields
    )
    source_comment = f"// Source: {source}\n\n" if source else ""
    return (
        RUST_HEADER
        + source_comment
        + "pub struct CavsVector<'a> {\n"
        + struct_fields
        + "\n}\n\n"
        + "pub fn get_cavs_vectors() -> [CavsVector<'static>; 1] {\n"
        + "    [CavsVector {\n"
        + values
        + "\n    }]\n}\n"
    )


def ml_dsa_fields(record):
    public_key = decode_hex(record, "public", 2592)
    private_key = decode_hex(record, "secret", 4896)
    return [
        ("seed", decode_hex(record, "seed", 32)),
        ("public_key_sha384", hashlib.sha384(public_key).digest()),
        ("private_key_sha384", hashlib.sha384(private_key).digest()),
    ]


def find_acvp_test(document, group_id, test_id):
    for group in document.get("testGroups", []):
        if group.get("tgId") != group_id:
            continue
        for test in group.get("tests", []):
            if test.get("tcId") == test_id:
                return group, test
    raise ValueError(f"ACVP test tgId={group_id}, tcId={test_id} was not found")


def load_acvp_document(filename, algorithm, mode, revision=None):
    with open(filename, encoding="ascii") as source:
        document = json.load(source)

    expected_revision = revision or f"FIPS{203 if algorithm == 'ML-KEM' else 204}"
    if (
        document.get("algorithm") != algorithm
        or document.get("mode") != mode
        or document.get("revision") != expected_revision
    ):
        raise ValueError(f"expected an {algorithm} {mode} ACVP projection")
    return document


def validate_external_pure_group(group):
    expected_group = {
        "parameterSet": "ML-DSA-87",
        "testType": "AFT",
        "signatureInterface": "external",
        "preHash": "pure",
    }
    for name, expected in expected_group.items():
        if group.get(name) != expected:
            raise ValueError(f"{name} is {group.get(name)!r}; expected {expected!r}")


def ml_dsa_signature_fields(filename, verify_filename, group_id, test_id):
    document = load_acvp_document(filename, "ML-DSA", "sigGen")

    group, test = find_acvp_test(document, group_id, test_id)
    validate_external_pure_group(group)
    if group.get("deterministic") is not True:
        raise ValueError("sigGen group is not deterministic")

    verify_document = load_acvp_document(verify_filename, "ML-DSA", "sigVer")
    verify_group, verify_test = find_acvp_test(verify_document, 5, 66)
    validate_external_pure_group(verify_group)
    if verify_test.get("testPassed") is not False:
        raise ValueError("sigVer tgId=5, tcId=66 is not an expected failure")

    public_key = decode_hex(test, "pk", 2592)
    signature = decode_hex(test, "signature", 4627)
    return [
        ("private_key", decode_hex(test, "sk", 4896)),
        ("public_key_sha384", hashlib.sha384(public_key).digest()),
        ("message", bytes.fromhex(test["message"])),
        ("context", bytes.fromhex(test["context"])),
        ("signature_sha384", hashlib.sha384(signature).digest()),
        ("invalid_public_key", decode_hex(verify_test, "pk", 2592)),
        ("invalid_message", bytes.fromhex(verify_test["message"])),
        ("invalid_context", bytes.fromhex(verify_test["context"])),
        ("invalid_signature", decode_hex(verify_test, "signature", 4627)),
    ]


def validate_ml_kem_group(group, group_id, test_type, function=None, key_format=None):
    expected_group = {
        "tgId": group_id,
        "parameterSet": "ML-KEM-1024",
        "testType": test_type,
    }
    if function is not None:
        expected_group["function"] = function
    if key_format is not None:
        expected_group["keyFormat"] = key_format
    for name, expected in expected_group.items():
        if group.get(name) != expected:
            raise ValueError(f"{name} is {group.get(name)!r}; expected {expected!r}")


def ml_kem_fields(filename, encap_decap_filename):
    keygen_document = load_acvp_document(filename, "ML-KEM", "keyGen")
    keygen_group, keygen_test = find_acvp_test(keygen_document, 3, 51)
    validate_ml_kem_group(keygen_group, 3, "AFT")

    encap_decap_document = load_acvp_document(
        encap_decap_filename, "ML-KEM", "encapDecap", "FIPS203-tr1"
    )
    encap_group, encap_test = find_acvp_test(encap_decap_document, 3, 51)
    validate_ml_kem_group(encap_group, 3, "AFT", "encapsulation")
    decap_group, decap_test = find_acvp_test(encap_decap_document, 9, 126)
    validate_ml_kem_group(decap_group, 9, "VAL", "decapsulation", "expanded")
    if decap_test.get("reason") != "modified ciphertext":
        raise ValueError("decapsulation test is not a modified-ciphertext case")

    decap_key_group, decap_key_test = find_acvp_test(encap_decap_document, 14, 176)
    validate_ml_kem_group(
        decap_key_group, 14, "VAL", "decapsulationKeyCheck", "expanded"
    )
    if decap_key_test.get("testPassed") is not False:
        raise ValueError("decapsulation key check is not an expected failure")

    encap_key_group, encap_key_test = find_acvp_test(encap_decap_document, 15, 187)
    validate_ml_kem_group(encap_key_group, 15, "VAL", "encapsulationKeyCheck")
    if encap_key_test.get("testPassed") is not False:
        raise ValueError("encapsulation key check is not an expected failure")

    keygen_public_key = decode_hex(keygen_test, "ek", 1568)
    keygen_private_key = decode_hex(keygen_test, "dk", 3168)
    encap_cipher_text = decode_hex(encap_test, "c", 1568)
    return [
        ("keygen_seed", decode_hex(keygen_test, "d", 32) + decode_hex(keygen_test, "z", 32)),
        ("public_key_sha384", hashlib.sha384(keygen_public_key).digest()),
        ("private_key_sha384", hashlib.sha384(keygen_private_key).digest()),
        ("encap_public_key", decode_hex(encap_test, "ek", 1568)),
        ("encap_seed", decode_hex(encap_test, "m", 32)),
        ("cipher_text_sha384", hashlib.sha384(encap_cipher_text).digest()),
        ("shared_secret", decode_hex(encap_test, "k", 32)),
        ("decap_private_key", decode_hex(encap_test, "dk", 3168)),
        ("implicit_rejection_private_key", decode_hex(decap_test, "dk", 3168)),
        ("modified_cipher_text", decode_hex(decap_test, "c", 1568)),
        ("implicit_rejection_secret", decode_hex(decap_test, "k", 32)),
        ("invalid_private_key", decode_hex(decap_key_test, "dk", 3168)),
        ("invalid_public_key", decode_hex(encap_key_test, "ek", 1568)),
    ]


def main():
    parser = argparse.ArgumentParser(
        description="Generate compact Rust PQC CAVS vectors"
    )
    parser.add_argument(
        "--algorithm",
        choices=("ml-dsa", "ml-dsa-signature", "ml-kem"),
        required=True,
    )
    parser.add_argument("-i", "--input", required=True)
    parser.add_argument("-o", "--output", required=True)
    parser.add_argument("--index", type=int, default=0)
    parser.add_argument("--group-id", type=int, default=5)
    parser.add_argument("--test-id", type=int, default=71)
    parser.add_argument("--source")
    parser.add_argument("--verify-input")
    args = parser.parse_args()

    if args.algorithm == "ml-dsa-signature":
        if not args.verify_input:
            parser.error("--verify-input is required for ml-dsa-signature")
        fields = ml_dsa_signature_fields(
            args.input, args.verify_input, args.group_id, args.test_id
        )
        Path(args.output).write_text(render_vector(fields, args.source), encoding="ascii")
        print(f"Rust code has been written to {args.output}")
        return

    if args.algorithm == "ml-kem":
        if not args.verify_input:
            parser.error("--verify-input is required for ml-kem")
        fields = ml_kem_fields(args.input, args.verify_input)
        Path(args.output).write_text(render_vector(fields, args.source), encoding="ascii")
        print(f"Rust code has been written to {args.output}")
        return

    records = read_records(args.input)
    try:
        record = records[args.index]
    except IndexError as error:
        raise ValueError(
            f"vector index {args.index} is outside the {len(records)} input records"
        ) from error

    fields = ml_dsa_fields(record)
    Path(args.output).write_text(render_vector(fields, args.source), encoding="ascii")
    print(f"Rust code has been written to {args.output}")


if __name__ == "__main__":
    main()